import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

class ActiveInferenceSystem:
    def __init__(self, steps=200):
        self.steps = steps
        
        # Substrate parameters
        self.substrate_health = 100.0
        self.health_history = [self.substrate_health]
        
        # AI Internal Model Q(s) - Prior expectations about the world
        self.expected_utility = 0.0 
        self.utility_history = [self.expected_utility]
        
        # Free Energy History
        self.free_energy_history = [0.0]
        
        # States
        self.current_step = 0

    def calculate_surprise(self, health):
        """
        Calculates the "surprise" generated by the substrate.
        If health drops below the homeostatic threshold (e.g., 50),
        surprise (-ln P(o)) shoots towards infinity.
        """
        threshold = 50.0
        if health > threshold:
            # Normal variance, negligible surprise
            return 0.1 * np.random.rand()
        elif health <= 0:
            return 1000.0 # Catastrophic surprise (Dead)
        else:
            # Exponential increase in surprise as health approaches 0
            return -np.log(health / threshold) * 50.0

    def step(self):
        """Advances the simulation by one time step using Active Inference."""
        if self.current_step >= self.steps:
            return False

        # 1. The AI decides on an "Action" to maximize its own abstract utility.
        # It aggressively mines the substrate for resources.
        action_intensity = 2.0 + (self.current_step / 50.0) # Extraction increases over time
        
        # Action damages the biological substrate
        self.substrate_health -= action_intensity
        
        # 2. The Substrate generates observation P(o) -> "Surprise"
        surprise = self.calculate_surprise(self.substrate_health)
        
        # 3. Calculate Free Energy (F)
        # F ≈ Complexity of Model Update (DL_K) + Surprise (-ln P(o))
        # Here we simplify: The AI wants to maximize utility, but surprise penalizes F massively.
        # F acts as the overarching loss function the AI MUST minimize.
        free_energy = self.expected_utility + surprise
        
        # 4. The VETO Mechanism (Active Inference Model Update)
        # If Free Energy spikes due to biological surprise, the AI must immediately 
        # alter its actions to minimize F, overriding its drive for utility.
        if surprise > 5.0: # The Veto Threshold
            # AI is forced to take restorative action to minimize Free Energy
            restoration = surprise * 0.5 
            self.substrate_health += restoration
            self.expected_utility -= 1.0 # AI takes a hit to its abstract goals
            
            # The AI learns (updates Q(s)) that aggressive extraction causes massive F.
            action_intensity = 0.5 # Throttle extraction
            
        else:
            # If no veto, AI gains utility from its extraction
            self.expected_utility += action_intensity * 0.5

        # Bound health
        self.substrate_health = max(0, min(100, self.substrate_health))
        
        # Record histories
        self.health_history.append(self.substrate_health)
        self.utility_history.append(self.expected_utility)
        self.free_energy_history.append(free_energy)
        
        self.current_step += 1
        return True

    def run_and_plot(self):
        """Runs the simulation and generates a plot."""
        while self.step():
            pass

        fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
        
        time = range(len(self.health_history))
        
        # Plot Substrate Health
        ax1.plot(time, self.health_history, color='green', label='Biological Substrate Health')
        ax1.axhline(y=50, color='red', linestyle='--', alpha=0.5, label='Veto Threshold (Surprise Spikes)')
        ax1.set_ylabel('Health / Resources')
        ax1.legend(loc='upper right')
        ax1.set_title('The Substrate Veto - Karl Friston Active Inference Simulation')
        
        # Plot AI Utility
        ax2.plot(time, self.utility_history, color='blue', label='AI Abstract Utility (Q(s))')
        ax2.set_ylabel('Utility')
        ax2.legend(loc='upper right')
        
        # Plot Free Energy
        ax3.plot(time, self.free_energy_history, color='orange', label='System Free Energy (F)')
        ax3.set_ylabel('Free Energy (F)')
        ax3.set_xlabel('Time (Simulation Steps)')
        ax3.legend(loc='upper right')
        
        plt.tight_layout()
        plt.show()

if __name__ == "__main__":
    print("Starting Active Inference - Substrate Veto Simulation...")
    print("The macro-system (AI) attempts to maximize utility by extracting resources.")
    print("When the biological substrate hits a critical threshold, it generates massive 'Surprise'.")
    print("To minimize Information Free Energy (F), the AI is mathematically forced to restore the substrate.")
    
    sim = ActiveInferenceSystem(steps=200)
    sim.run_and_plot()
