"""
Latent vs. Introspective Agent Society Simulation
--------------------------------------------------
This simulation visualizes the "Cognitive Division of Labor" principle derived from
Asimov's Paradox and the Anthropic/OpenAI research divergence.

It runs three isolated societies in parallel grids:
1. 100% Latent Agents: Fast, 1-step vision, purely reactive. Prone to getting stuck.
2. 100% Introspective Agents: Perfect A* vision, but extremely slow (high cognitive load).
3. Symbiotic Society: Introspective agents act as "consciousness" (placing gradients),
   while Latent agents act as "muscle" (moving fast along gradients).

Goal: Gather randomly spawning resources.
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import time
from collections import deque

# --- Parameters ---
GRID_SIZE = 30
NUM_AGENTS = 10
NUM_RESOURCES = 5
SIM_STEPS = 500
INTROSPECTIVE_DELAY = 5 # They move/think 5x slower than Latent
PHEROMONE_DECAY = 0.95

# --- Utilities ---
def manhattan_distance(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

def get_neighbors(pos):
    y, x = pos
    neighbors = []
    for dy, dx in [(-1,0), (1,0), (0,-1), (0,1)]:
        ny, nx = y+dy, x+dx
        if 0 <= ny < GRID_SIZE and 0 <= nx < GRID_SIZE:
            neighbors.append((ny, nx))
    return neighbors

def bfs_distance_field(targets, obstacles=[]):
    """Simulates 'Perfect Vision / A*' - computationally heavy."""
    dist = np.full((GRID_SIZE, GRID_SIZE), 999.0)
    queue = deque()
    
    for t in targets:
        dist[t] = 0
        queue.append(t)
        
    while queue:
        curr = queue.popleft()
        d = dist[curr]
        for nxt in get_neighbors(curr):
            if nxt not in obstacles and dist[nxt] > d + 1:
                dist[nxt] = d + 1
                queue.append(nxt)
    return dist

# --- Base Society Class ---
class Society:
    def __init__(self, name, num_latent, num_introspective):
        self.name = name
        self.grid = np.zeros((GRID_SIZE, GRID_SIZE)) # 0: empty
        
        # Resources
        self.resources = set()
        for _ in range(NUM_RESOURCES):
            self.spawn_resource()
            
        # Pheromones (Meaning/Strategy map generated by introspectives)
        self.pheromones = np.zeros((GRID_SIZE, GRID_SIZE))
            
        # Agents: dict of id -> {pos, type, internal_timer}
        self.agents = {}
        for i in range(num_latent):
            pos = (np.random.randint(0, GRID_SIZE), np.random.randint(0, GRID_SIZE))
            self.agents[f"L_{i}"] = {"pos": pos, "type": "latent", "timer": 0}
            
        for i in range(num_introspective):
            pos = (np.random.randint(0, GRID_SIZE), np.random.randint(0, GRID_SIZE))
            self.agents[f"I_{i}"] = {"pos": pos, "type": "introspective", "timer": 0}
            
        self.score = 0

    def spawn_resource(self):
        while True:
            pos = (np.random.randint(0, GRID_SIZE), np.random.randint(0, GRID_SIZE))
            if pos not in self.resources:
                # Ensure no agent is there
                conflict = False
                for a in self.agents.values():
                    if a["pos"] == pos:
                        conflict = True
                        break
                if not conflict:
                    self.resources.add(pos)
                    break

    def step(self):
        # Decay external memory
        self.pheromones *= PHEROMONE_DECAY
        
        # Determine global target map for Introspectives
        # (They calculate the true distance to closest resource)
        if any(a["type"] == "introspective" for a in self.agents.values()):
            true_dist = bfs_distance_field(self.resources)
        
        for a_id, agent in self.agents.items():
            agent["timer"] += 1
            pos = agent["pos"]
            
            # 1. Latent Agent Logic (Runs every tick)
            if agent["type"] == "latent":
                # Look at immediate neighbors
                best_move = pos
                best_val = -float('inf')
                
                for nxt in get_neighbors(pos) + [pos]:
                    # Instinct 1: If I see a resource next to me, grab it
                    if nxt in self.resources:
                        best_move = nxt
                        break
                        
                    # Instinct 2: Follow Pheromones (External Meaning)
                    val = self.pheromones[nxt]
                    
                    # Add slight random noise to prevent infinite loops (Entropy)
                    val += np.random.rand() * 0.1
                    
                    if val > best_val:
                        best_val = val
                        best_move = nxt
                        
                agent["pos"] = best_move
                
            # 2. Introspective Agent Logic (Runs slowly, but alters environment)
            elif agent["type"] == "introspective":
                if agent["timer"] >= INTROSPECTIVE_DELAY:
                    agent["timer"] = 0
                    
                    # Perfect vision: move towards lowest true distance
                    best_move = pos
                    min_dist = true_dist[pos]
                    
                    for nxt in get_neighbors(pos):
                        if true_dist[nxt] < min_dist:
                            min_dist = true_dist[nxt]
                            best_move = nxt
                            
                    agent["pos"] = best_move
                    
                    # Downward Causation: Leave meaning (pheromones) for latents
                    # They drop a high value that guides latents to this "good" path
                    self.pheromones[pos] += 5.0
                    
            # Check resource collection
            if agent["pos"] in self.resources:
                self.resources.remove(agent["pos"])
                self.score += 1
                self.spawn_resource()

    def get_render_grid(self):
        # 0: empty, 1: latent, 2: introspective, 3: resource
        render = np.zeros((GRID_SIZE, GRID_SIZE))
        for r in self.resources:
            render[r] = 3
        for a in self.agents.values():
            if a["type"] == "latent":
                render[a["pos"]] = 1
            else:
                render[a["pos"]] = 2
        return render

# --- Visualization ---
def run_simulation(steps=SIM_STEPS):
    print("Starting Agentic Society Simulation...")
    print("Green = Resources, Blue = Latent Agents, Red = Introspective Agents")
    
    # Setup 3 societies
    # A: 10 Latent, 0 Intro
    soc_latent = Society("Pure Latent (Intuition Only)", NUM_AGENTS, 0)
    # B: 0 Latent, 10 Intro
    soc_intro = Society("Pure Introspective (Reflexion Only)", 0, NUM_AGENTS)
    # C: 5 Latent, 2 Intro (Less total agents, but symbiotic)
    soc_symbiotic = Society("Symbiotic (Action + Reflexion)", 7, 3)
    
    societies = [soc_latent, soc_intro, soc_symbiotic]
    
    plt.ion()
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    fig.canvas.manager.set_window_title('Cognitive Division of Labor in MAS')
    
    cmap = mcolors.ListedColormap(['#111111', '#00bfff', '#ff3366', '#33ff33'])
    norm = mcolors.BoundaryNorm([0, 1, 2, 3, 4], cmap.N)
    
    ims_grid = []
    ims_pher = []
    
    for i, soc in enumerate(societies):
        ax_g = axes[0, i]
        ax_p = axes[1, i]
        
        ax_g.set_title(soc.name)
        ims_grid.append(ax_g.imshow(soc.get_render_grid(), cmap=cmap, norm=norm))
        ax_g.axis('off')
        
        ax_p.set_title(f"{soc.name} Pheromones")
        ims_pher.append(ax_p.imshow(soc.pheromones, cmap='hot', vmin=0, vmax=5))
        ax_p.axis('off')
        
    scores = [0, 0, 0]
    
    try:
        for step in range(steps):
            if not plt.fignum_exists(fig.number):
                break
                
            for i, soc in enumerate(societies):
                soc.step()
                scores[i] = soc.score
                
                if step % 2 == 0:
                    ims_grid[i].set_data(soc.get_render_grid())
                    ims_pher[i].set_data(soc.pheromones)
                    axes[0, i].set_title(f"{soc.name}\nScore: {soc.score}")
            
            if step % 2 == 0:
                fig.canvas.draw()
                fig.canvas.flush_events()
                
            if step % 50 == 0:
                print(f"Step {step:03d} | Scores: L={scores[0]} | I={scores[1]} | Sym={scores[2]}")
                
    except KeyboardInterrupt:
        pass
        
    print("\n--- Final Results ---")
    for soc in societies:
        print(f"{soc.name}: {soc.score} resources gathered")
    
    plt.ioff()
    plt.show()

if __name__ == "__main__":
    run_simulation()
